version: '{build}'

branches:
  only:
    - master

platform:
  - x64

image:
  - Visual Studio 2019

init:
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator="Visual Studio 16 2019 -A x64" )
- echo %generator%

matrix:
  fast_finish: true

before_build:
  - "cd tests"
  - "mkdir build"
  - "cd build"
  - cmake --version
  - cmake .. -G %generator%

build:
  project: C:/projects/fastor/tests/build/test_fastor.sln
  verbosity: minimal