version: '{build}'

branches:
  only:
    - master

platform:
  - x64

image:
  - Visual Studio 2019

matrix:
  fast_finish: true

before_build:
  - "cd tests"
  - "mkdir build"
  - "cd build"
  - cmake --version
  - cmake ..

build:
  project: C:/projects/fastor/tests/build/test_fastor.sln
  verbosity: normal