language: cpp

os:
  - linux

dist: bionic

compiler:
  - gcc
  - clang

before_install:
  - FASTORPATH=$(pwd)
  - echo $FASTORPATH

install:
  # build the tests
  - cd ~
  - cd $FASTORPATH/tests
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ../
  - make -j2

script:
  # Run the test suite
  - cd ~
  - cd $FASTORPATH/tests/build/
  - ctest -V


notifications:
  email: false